security:
    encoders:
        FOS\UserBundle\Model\UserInterface: sha512

    role_hierarchy:
        ROLE_ELEVE:       ROLE_USER
        ROLE_SUIVEUR:     [ ROLE_USER, ROLE_ELEVE]
        ROLE_TRESO:       [ ROLE_USER, ROLE_ELEVE]
        ROLE_CA:          [ ROLE_USER, ROLE_ELEVE, ROLE_SUIVEUR]
        ROLE_ADMIN:       [ ROLE_USER, ROLE_ELEVE, ROLE_SUIVEUR, ROLE_CA]
        ROLE_SUPER_ADMIN: [ ROLE_USER, ROLE_ELEVE, ROLE_SUIVEUR, ROLE_CA, ROLE_ADMIN, ROLE_ALLOWED_TO_SWITCH, ROLE_TRESO ]

    providers:
        fos_userbundle:
            id: fos_user.user_provider.username

    firewalls:
        main:
            pattern: ^/
            form_login:
                provider:      fos_userbundle
                csrf_provider: security.csrf.token_manager
            logout:    true
            anonymous: true

    access_control:
        - { path: ^/(_(profiler|wdt|error)|css|images|js), roles: IS_AUTHENTICATED_ANONYMOUSLY }

        - { path: ^/login$, role: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/register, role: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/resetting, role: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/admin/, role: ROLE_CA }
        - { path: ^/over/, role: ROLE_SUPER_ADMIN }

        # PAGES ACCESSIBLES AUX SUIVEUR
        - { path: ^/suivi/*, role: ROLE_SUIVEUR }

        # PAGES ACCESSIBLES AUX UTILISATEURS CONNECTES
        - { path: ^/.*, role: ROLE_USER }
