Mgate_publi_publiposter:
    path: /Documents/Publiposter/{templateName}/{rootName}/{rootObject_id}
    defaults: {_controller: MgatePubliBundle:Traitement:publiposter}
    requirements:
        rootObject_id:  \d+
        rootName: \w+
        templateName: \w+
    methods:  [GET, HEAD, POST]

Mgate_publi_telecharger:
    path: /publi/publiposter/telecharger
    defaults: {_controller: MgatePubliBundle:Traitement:telecharger}
    methods:  [GET, HEAD, POST]

Mgate_publi_documenttype_upload:
    path: /DocumentsType/Upload
    defaults: {_controller: MgatePubliBundle:Traitement:uploadNewDoctype}
    methods:  [GET, HEAD, POST]

#Export du Gantt seul.
Mgate_publi_getgantt:
    path: /Documents/GetGantt/{id}/{width}
    defaults: {_controller: MgatePubliBundle:Gantt:getGantt, width: 960}
    requirements:
        id:  \d+
        width: \d+
    methods:  [GET, HEAD]

######################
# UPLOAD DE DOCUMENT #
######################
Mgate_publi_documenttype_index:
    path: /Documents/
    defaults: {_controller: MgatePubliBundle:Document:index}
    methods:  [GET, HEAD]

Mgate_publi_document_uploadEtude:
    path: /Documents/Upload/Etude/{etude_id}
    defaults: {_controller: MgatePubliBundle:Document:uploadEtude}
    requirements:
        etude_id:  \d+
    methods:  [GET, HEAD, POST]

Mgate_publi_document_uploadEtudiant:
    path: /Documents/Upload/Etudiant/{membre_id}
    defaults: {_controller: MgatePubliBundle:Document:uploadEtudiant}
    requirements:
        membre_id:  \d+
    methods:  [GET, HEAD, POST]

Mgate_publi_document_uploadFormation:
    path: /Documents/Upload/Formation/{id}
    defaults: {_controller: MgatePubliBundle:Document:uploadFormation}
    requirements:
        id:  \d+
    methods:  [GET, HEAD]

Mgate_publi_document_uploadDoctype:
    path: /Documents/Upload/Doctype
    defaults: {_controller: MgatePubliBundle:Document:uploadDoctype}
    methods:  [GET, HEAD, POST]

Mgate_publi_document_delete:
    path: /Documents/Supprimer/{id}
    defaults: {_controller: MgatePubliBundle:Document:delete}
    requirements:
        id:  \d+
    methods:  [GET, HEAD, POST]

Mgate_publi_import:
    path: /Documents/import
    defaults: {_controller: MgatePubliBundle:Import:index}
    methods:  [GET, HEAD, POST]

Mgate_publi_import_format:
    path: /Documents/import/format/{service_number}
    defaults: {_controller: MgatePubliBundle:Import:ajaxExpectedFormat}
    methods:  [GET, HEAD]

