symfony_src_dir: symfony-app
symfony_owner:   vagrant

doc_root: /var/www/symfony-app/web

sys_packages:
  - curl
  - mcrypt
  - wget

php_packages:
  - { name: dev, package: php5-dev }
  - { name: pear, package: php-pear }
  - { name: xdebug, package: php5-xdebug }
  - { name: curl, package: php5-curl }
  - { name: mcrypt, package: php5-mcrypt }
  - { name: mysql, package: php5-mysql }
  - { name: redis, package: php5-redis }

php_extensions:
  - { name: jsmin, package: pecl.php.net/jsmin-beta }
  - { name: xhprof, package: pecl.php.net/xhprof-beta }

php_ppa: php5

php_global_settings_override:
  date.timezone: Europe/Paris

# TODO: cf issue https://github.com/knopki/ansible-locale/issues/5
# Maybe use https://github.com/knopki as module instead of our custom?
locale:          fr_FR.UTF-8
locale_language: fr
locale_ctype:    fr_FR.UTF-8

composer_path: /usr/bin/composer
